name: Auto Version
description: Auto bump versions if not already bumped

inputs:
  author_name:
    description: 'Author name to use for the commit'
    required: true
  author_email:
    description: 'Author email to use for the commit'
    required: true

runs:
  using: composite
  steps:
    - name: Get package versions
      run: |
        git fetch origin main
        MAIN_VERSION=$(jq -r '.version' <(git show origin/main:package.json))
        CURRENT_VERSION=$(jq -r '.version' package.json)
        echo "Main version: $MAIN_VERSION"
        echo "Current version: $CURRENT_VERSION"
        echo MAIN_VERSION=$MAIN_VERSION >> $GITHUB_ENV
        echo CURRENT_VERSION=$CURRENT_VERSION >> $GITHUB_ENV
      shell: bash

    - name: Auto bump version if not already done
      if: env.CURRENT_VERSION && env.MAIN_VERSION == env.CURRENT_VERSION
      run: |
        git config user.name '[CI] for ${{ inputs.author_name }}'
        git config user.email '${{ inputs.author_email }}'
        npm version -ws --include-workspace-root --no-git-tag-version patch
        ver=$(jq -r '.version' package.json)
        git add --all
        git commit -m "[CI] Auto bumped package versions to '$ver'"
        git push
      shell: bash
