name: ♺ auto bump versions

on:
  pull_request_review:
    types: submitted

jobs:
  Show-Context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github event state
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: |
          echo "github.event: $GITHUB_CONTEXT"

  Version:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Count approvals on current pull request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Counting approvals..."
          reviews=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews)
          approvals=$(echo "$reviews" | jq '[.[] | select(.state == "APPROVED")] | length')
          echo "Number of unique approvals: $approvals"
          echo "approvals=$approvals" >> $GITHUB_ENV

      - name: Auto patch packages versions
        if: ${{ github.env.approvals >= 2 }}
        run: |
          echo "Auto patching packages versions..."
