name: ♺ auto bump versions

on:
  pull_request_review:
    types: [submitted, edited]

jobs:
  Show-Context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github event state
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: |
          echo "github.event: $GITHUB_CONTEXT"

  Version:
    runs-on: ubuntu-latest
    steps:
      - name: Auto patch packages versions
        run: |
          echo "Auto patching packages versions..."
