name: Push to main branch

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"

jobs:
  Deploy-dev:
    uses: ./.github/workflows/deploy.yml
    with:
      env: dev
    secrets: inherit
