name: Deploy dev ➤

on:
  workflow_dispatch:
    inputs:
      component:
        description: "Component to deploy"
        required: true
        type: choice
        default: "all"
        options:
          - all
          - backend
          - frontend

jobs:
  Deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      env: dev
      component: ${{ inputs.component }}
    secrets: inherit
