name: Release to int environment

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-int

jobs:
  Check-main-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check main branch
        run: |
          if [ "${GITHUB_REF}" != "refs/heads/main" ]; then
            echo "This action can only be run on the main branch"
            exit 1
          fi
        shell: bash
  Deploy-int:
    uses: ./.github/workflows/_deploy.yml
    with:
      env: int
    secrets: inherit
