name: Release to int environment

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-int
      - v[0-9]+.[0-9]+.[0-9]+-int.*

jobs:
  Deploy-int:
    uses: ./.github/workflows/_deploy.yml
    with:
      env: int
    secrets: inherit
