name: Release to prod environment

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  Deploy-prod:
    uses: ./.github/workflows/_deploy.yml
    with:
      env: prod
    secrets: inherit
